import { useState } from 'react';
import { api } from './api';

/**
 * AiInsights — AI weak-area analysis for one student, grounded in their
 * assessment scores (POST /students/:id/insights).
 *
 * The backend always returns rule-based weakest-topics + focus plan; the AI
 * narrative layer is best-effort (badge shows which one you got).
 */
export default function AiInsights({ studentId }) {
  const [state, setState] = useState({ status: 'idle' });

  const run = async () => {
    if (state.status === 'loading') return;
    setState({ status: 'loading' });
    try {
      const data = await api.studentInsights(studentId);
      setState({ status: 'done', data });
    } catch (e) {
      setState({ status: 'error', error: e.message || 'Could not generate insights' });
    }
  };

  if (state.status === 'idle') {
    return (
      <div className="card mt">
        <h4>AI Weak-Area Analysis</h4>
        <p className="meta" style={{ margin: '0 0 10px' }}>
          Identifies weak topics from assessment scores, compares against batch averages, and suggests what to study next.
        </p>
        <button type="button" className="btn sm" onClick={run}>Analyze with AI</button>
      </div>
    );
  }

  if (state.status === 'loading') {
    return (
      <div className="card mt">
        <h4>AI Weak-Area Analysis</h4>
        <p className="meta">Analyzing assessment performance…</p>
      </div>
    );
  }

  if (state.status === 'error') {
    return (
      <div className="card mt">
        <h4>AI Weak-Area Analysis</h4>
        <div className="err">{state.error}</div>
        <button type="button" className="btn sm ghost" onClick={run} style={{ marginTop: 8 }}>Try again</button>
      </div>
    );
  }

  const d = state.data;
  return (
    <div className="card mt">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
        <h4 style={{ margin: 0 }}>AI Weak-Area Analysis</h4>
        <span className={'chip ' + (d.ai ? 'PAID' : 'LATE')} title={d.ai ? `Generated by ${d.model || 'AI'}` : (d.notice || 'Rule-based analysis')}>
          {d.ai ? '✦ AI-powered' : 'Rule-based'}
        </span>
      </div>

      {d.stats && (
        <p className="meta" style={{ margin: '8px 0 0' }}>
          {d.stats.assessed_count} assessment{d.stats.assessed_count === 1 ? '' : 's'} analyzed
          {d.stats.avg_pct != null && <> · Avg <b>{d.stats.avg_pct}%</b></>}
          {d.stats.attendance_pct != null && <> · Attendance <b>{d.stats.attendance_pct}%</b></>}
          {d.stats.trend && d.stats.trend !== '—' && <> · Trend <b>{d.stats.trend}</b></>}
        </p>
      )}

      {d.narrative && (
        <p style={{ fontSize: 13.5, lineHeight: 1.6, color: '#334155', whiteSpace: 'pre-line', margin: '10px 0 0' }}>
          {d.narrative}
        </p>
      )}
      {!d.ai && d.notice && <p className="meta" style={{ margin: '8px 0 0' }}>{d.notice}</p>}

      {d.weakest?.length > 0 && (
        <>
          <h4 style={{ margin: '14px 0 6px' }}>Weakest topics</h4>
          <div className="list">
            {d.weakest.map((w, i) => (
              <div className="list-row" key={i}>
                <span className="grow">
                  <b>{w.topic}</b>
                  {w.batch_avg != null && <span className="meta"> · batch avg {w.batch_avg}%</span>}
                </span>
                <div className={'bar fixed' + (w.pct < 60 ? ' bad' : ' ok')}>
                  <i style={{ width: `${w.pct}%` }} />
                </div>
                <b className="amt">{w.pct}%</b>
              </div>
            ))}
          </div>
        </>
      )}

      {d.strengths?.length > 0 && (
        <p className="meta" style={{ margin: '10px 0 0' }}>
          Strengths: {d.strengths.map((s) => `${s.topic} (${s.pct}%)`).join(', ')}
        </p>
      )}

      {d.plan?.length > 0 && (
        <>
          <h4 style={{ margin: '14px 0 6px' }}>Focus plan</h4>
          <div className="list">
            {d.plan.map((p, i) => (
              <div className="list-row" key={i}>
                <span className="grow" style={{ fontSize: 13 }}>{i + 1}. {p}</span>
              </div>
            ))}
          </div>
        </>
      )}

      <button type="button" className="btn sm ghost" onClick={run} style={{ marginTop: 10 }}>Re-analyze</button>
    </div>
  );
}
